name: jabalprog
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    #images

    - assets/
    - assets/images/app/
    - assets/images/code/

    #fonts
    - assets/fonts/ubuntu/
    - assets/fonts/ubuntu/Ubuntu-Light.ttf
    - assets/fonts/ubuntu/Ubuntu-Regular.ttf
    - assets/fonts/ubuntu/Ubuntu-Medium.ttf
    - assets/fonts/ubuntu/Ubuntu-Bold.ttf
